const texts = [
	`The belief that "There is no god but God, and Muhammad is the Messenger of God" is central to Islam. This phrase, written in Arabic, is often prominently featured in architecture and a range of objects, including the Qur'an, Islam's holy book of divine revelations. One becomes a Muslim by reciting this phrase with conviction.`,

	`Muslims pray facing Mecca five times a day: at dawn, noon, mid-afternoon, sunset, and after dark. Prayer includes a recitation of the opening chapter (sura) of the Qur'an, and is sometimes performed on a small rug or mat used expressly for this purpose. Muslims can pray individually at any location or together in a mosque,`,

	`where a leader in prayer (imam) guides the congregation. Men gather in the mosque for the noonday prayer on Friday; women are welcome but not obliged to participate. After the prayer, a sermon focuses on a passage from the Qur'an, followed by prayers by the imam and a discussion of a particular religious topic.`,

	`In accordance with Islamic law, Muslims donate a fixed portion of their income to community members in need. Many rulers and wealthy Muslims build mosques, drinking fountains, hospitals, schools, and other institutions both as a religious duty and to secure the blessings associated with charity.`,

	`During the daylight hours of Ramadan, the ninth month of the Islamic calendar, all healthy adult Muslims are required to abstain from food and drink. Through this temporary deprivation, they renew their awareness of and gratitude for everything God has provided in their lives-including the Qur'an, which was first revealed during this month.`,

	`What Does 'Islam' Mean? "Islam" is an Arabic term which means to submit one's will to the will of God. Islam is a monotheistic religion that teaches that there is only one divine being, one supreme Creator of the universe. Muslims believe that Islam is the true religion of God revealed to humanity. It is a universal religion that can be practiced by anyone at any time and in every place. The central concept of this way of life is total submission to God. Islam is a complete, holistic way of living that covers every aspect of life. Islam leaves no stone unturned as it teaches mankind on how to behave in every area of life: individual, social, material, moral, ethical, legal, cultural, political, economical, and global.`,

	`What is a Muslim? A Muslim is anyone who submits their will to the one and only true God who is worthy of worship, "Allah" (God). A Muslim also believes in the Prophet Muhammad (peace be upon him) as the last and final prophet of God. By submitting oneself and worshiping Allah (God), a Muslim attains peace through obedience to his commandments. Peace is a natural result of submitting to the will of Allah.`,

	`Who is Allah? Allah is the name God Almighty has given Himself as is mentioned many times in the Holy Quran; Say: He is Allah, (the) One; Allah, the Eternal; He did not beget (give birth) and He was not begotten (given birth to); And there has never been anyone equal to Him.`,

	`What are the 6 Pillars? Faith in Islam stands on six pillars and this was taught to the Muslims in a famous narration of the Prophet (peace be upon him). He said: Faith means to believe in Allah, His angels, His Books, His Messengers, the Last Day, and the Divine Decree, both good and bad.`,

	`Belief in the Revealed Scriptures: In Islam it is a part of faith to believe all the books that were revealed to the messengers. There have been many scriptures revealed throughout the history of mankind. Allah tells us about a few of the names of the scriptures in the Qur'an. They include the Torah which was sent to Moses, the Gospel which was sent to Jesus, the Psalms (Zaboor) which was sent to David, the scriptures of Ibrahim (Abraham), and the Qur'an itself which was sent to Muhammad (peace be upon them all).`,

	`There are 25 messengers who have been mentioned by name in the Qur'an. They include: Adam, Idrees, Nooh (Noah), Hood, Salih, Ibrahim (Abraham), Lut (Lot), Ismail, Ishaq (Isaac), Ya'qoob (Jacob), Yusuf (Joseph), Shu'ayb, Ayoob (Job), Dhu'l-Kifl, Moosa (Moses), Haroon (Aaron), Dawood (David), Sulaymaan (Solomon), Ilyaas (Elias), al-Yasa', Yunus (Jonah), Zakaria, Yahya, 'Isa (Jesus) and Muhammad - blessings and peace be upon them all.`,

	`Muhammad (peace be upon him) was born during the year 570 according to the Gregorian calendar in the city of Makkah. He was an orphan as his father passed away before he was born. When he was six years old he embarked on a journey with his mother Aminah to a different city called Madinah to visit his maternal uncles. On their way back to Makkah his mother passed away in a city known as al-Abwaa. Both of his parents were gone before his 7th birthday. Soon afterwards his grandfather Abd al-Muttalib became his guardian. However, just a few short years later his grandfather also passed away when Muhammad (peace be upon him) was eight years old. Before reaching the age of 10 his mother, father, and grandfather were no longer in his life. He was deprived of parental love at a very young age. After their passing Muhammad (peace be upon him) was raised by his paternal uncle, Abu Talib. His uncle was a respected community leader in Makkah. Abu Talib became his new guardian, treated him with care, compassion, and helped him grow into a fine young man.`,

	`As Muhammad (peace be upon him) was growing into a young adult the community started to take notice of him. He built a good reputation for himself as he would tend sheep for the people of Makkah, safeguard their possessions, speak the truth, be reserved in his demeanor, and use sound judgement. Well before prophethood he was the best of his people in character and in attitude. He was known for being generous, patient, truthful, and sincere. The people of Makkah admired his noble character and gave him the title al-Ameen (the trustworthy). He later found employment with a successful merchant in Makkah by the name of Khadija. She had a reputation for being a savvy businessperson. He became one of Khadija's agents and would travel on behalf of her to do business in Syria. Khadija was very impressed with his good character, honesty, and sincerity. Khadija would eventually take an interest in him, and not long after the two would get married. Muhammad (peace be upon him) married Khadija at the age of 25.`,

	`Muhammad (peace be upon him) received his first revelation while in a cave called Hira on the outskirts of Makkah. This cave was a place where he used to go to regularly for spiritual retreats and to perform worship. One day during one of his retreats in the year 610, at the time he was 40 years old, the angel Jibreel (Gabriel) suddenly appeared before him. The angel came to him and asked him to read. The Prophet (peace be upon him) replied, “I do not know how to read.” The Prophet (peace be upon him) added, “The angel caught me (forcefully) and pressed me so hard that I could not bear it any more. He then released me and again asked me to read and I replied, 'I do not know how to read.' Thereupon he caught me again and pressed me a second time till I could not bear it any more. He then released me and again asked me to read but again I replied, 'I do not know how to read (or what shall I read)?' Thereupon he caught me for the third time and pressed me, and then released me and said, Read! In the Name of your Lord Who has created (all that exists). He has created man from a clot (a piece of thick coagulated blood). Read! And your Lord is the Most Generous`,

	`The Prophet (peace be upon him) stayed in Makkah for 13 years calling to monotheism: worshiping Allah alone without any partner. He started to call people to the religion in secret with a small group of people. This group of people were very close to him which included relatives from within Quraysh, the clan the Prophet’s family is from. He later started to call large groups of people to embrace Islam, believe in one God, and believe in him as a Prophet. Only a small number of Muslims believed in his message in the early years of Prophethood and those who believed were prosecuted by the people of Makkah. Some were tortured and others were killed. Many of the people who were plotting to harm the Muslims included members from within the Quraysh. To help keep the Muslims away from further prosecution Muhammad (peace be upon him) later commanded some of the Muslims to migrate to Abyssinia (modern day Eritrea and the northern half of Ethiopia). The King of Abyssinia allowed the migrant Muslims to stay within his lands where they were safe from being harmed.`,
];

export default texts;
